package thut.core.common.commands;

import net.minecraft.command.ICommandSender;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.TextComponentTranslation;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.server.permission.DefaultPermissionLevel;
import net.minecraftforge.server.permission.PermissionAPI;

public class CommandTools
{
    public static boolean isOp(ICommandSender sender, String permission)
    {
        /*
         * If sent by a player, check permissions, otherwise return true.
         */
        if (sender instanceof EntityPlayerMP)
        {
            /*
             * Check if the node is registered, if not, register it as OP, and
             * send error message about this.
             */
            if (!PermissionAPI.getPermissionHandler().getRegisteredNodes().contains(permission))
            {
                String message = "Autogenerated node, this is a bug and should be pre-registered.";
                PermissionAPI.getPermissionHandler().registerNode(permission, DefaultPermissionLevel.OP, message);
                System.err.println(message + ": " + permission);
            }
            return PermissionAPI.hasPermission((EntityPlayerMP) sender, permission);
        }
        return true;
    }

    public static ITextComponent makeError(String text)
    {
        return makeTranslatedMessage(text, "red:italic");
    }

    public static ITextComponent makeTranslatedMessage(String key, String formatting, Object... args)
    {
        if (formatting == null) formatting = "";
        for (int i = 0; i < args.length; i++)
        {
            if (args[i] instanceof String)
            {
                args[i] = new TextComponentTranslation((String) args[i]);
            }

            if (!formatting.isEmpty() && args[i] instanceof ITextComponent)
            {
                ITextComponent component = (ITextComponent) args[i];
                String[] args2 = formatting.split(":");
                String colour = args2[0].toUpperCase(java.util.Locale.ENGLISH);
                component.getStyle().setColor(TextFormatting.getValueByName(colour));
                if (args2.length > 1)
                {
                    for (int i1 = 1; i1 < args2.length; i1++)
                    {
                        String arg = args2[i1];
                        if (arg.equalsIgnoreCase("italic"))
                        {
                            component.getStyle().setItalic(true);
                        }
                        if (arg.equalsIgnoreCase("bold"))
                        {
                            component.getStyle().setBold(true);
                        }
                        if (arg.equalsIgnoreCase("underlined"))
                        {
                            component.getStyle().setUnderlined(true);
                        }
                        if (arg.equalsIgnoreCase("strikethrough"))
                        {
                            component.getStyle().setStrikethrough(true);
                        }
                        if (arg.equalsIgnoreCase("obfuscated"))
                        {
                            component.getStyle().setObfuscated(true);
                        }
                    }
                }
            }
        }
        TextComponentTranslation translated = new TextComponentTranslation(key, args);
        return translated;
    }

    public static void sendBadArgumentsMissingArg(ICommandSender sender)
    {
        sender.sendMessage(makeError("pokecube.command.invalidmissing"));
    }

    public static void sendBadArgumentsTryTab(ICommandSender sender)
    {
        sender.sendMessage(makeError("pokecube.command.invalidtab"));
    }

    public static void sendError(ICommandSender sender, String text)
    {
        sender.sendMessage(makeError(text));
    }

    public static void sendMessage(ICommandSender sender, String text)
    {
        ITextComponent message = makeTranslatedMessage(text, null);
        sender.sendMessage(message);
    }

    public static void sendNoPermissions(ICommandSender sender)
    {
        sender.sendMessage(makeError("pokecube.command.noperms"));
    }
}
